[[constraint]]
  name = "github.com/docopt/docopt-go"
  revision = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1"

[[constraint]]
  name = "github.com/go-telegram-bot-api/telegram-bot-api"
  version = "4.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/noam09/go-couchpotato-api"

[prune]
  go-tests = true
  unused-packages = true
