[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[constraint]]
  name = "github.com/go-telegram-bot-api/telegram-bot-api"
  version = "4.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/noam09/go-couchpotato-api"

[prune]
  go-tests = true
  unused-packages = true
